[daemon]
AutomaticLoginEnable=True
AutomaticLogin=devsec

[security]

[xdmcp]

[chooser]

[debug]
# Uncomment the line below to turn on debugging
# More verbose logs
# Additionally lets determine the logfile for debug logs of the daemon
#Enable=true
